[project]
name = "dash-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plotly",
    "dash>=4.1.0",
    "dash-iconify>=0.1.2",
    "ruff>=0.12.1",
    "dash-ag-grid>=31.3.1",
    "pandas>=2.2.3",
    "gunicorn>=23.0.0",
    "requests>=2.32.3",
    "python-dotenv>=1.2.3",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 100
