FROM git.ltplabs.net:5050/libs/custom-docker-images/py-3.11-slim-uv

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV PATH="/root/.local/bin:$PATH"

RUN apt-get update && apt-get install --no-install-recommends -y curl build-essential

WORKDIR /app

COPY plotly_webapp/pyproject.toml plotly_webapp/uv.lock plotly_webapp/.python-version ./


RUN uv sync
COPY ./plotly_webapp/ .

# Run command
CMD ["uv", "run", "gunicorn", "-b", "0.0.0.0:8050", "-w", "4", "-t", "60", "app:app"]
